### ISSUE TITLE
FlashStart configuration fails

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#411]
On a clean machine, FlashStart can't be configured.

**Steps to reproduce**

- Install a clean machine, make sure to configure the WAN interface with DHCP
- Access the "FlashStart filter" page under under "Security"
- Enable and configure the server, then click "Save"

**Expected behavior**

FlashStart filter should start.

**Actual behavior**

The UI returns a server error:
```
Request failed
ns.flashstart set-config
```

Executed command:
```
echo '{"enabled":true,"username":"user@yyy.zzz","password":"xxx","zones":["lan"],"bypass":[]}' | /usr/libexec/rpcd/ns.flashstart call set-config
Traceback (most recent call last):
  File "/usr/libexec/rpcd/ns.flashstart", line 62, in <module>
    e_uci.get('dhcp', dnsmasq, 'server', list=True))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/euci/__init__.py", line 85, in get
uci.UciExceptionNotFound
```

**Components**

Version: 8-23.05.3-ns.0.0.3-rc1

Packages:
```
ns-api - 0.0.59-1
ns-api-server - 0.0.14-1
ns-dedalo - 0.0.2-1
ns-don - 0.0.1-1
ns-dpi - 0.0.2-1
ns-flashstart - 0.0.3-1
ns-migration - 0.0.5-1
ns-netmap - 0.0.2-1
ns-objects - 0.0.1-1
ns-openvpn - 0.0.1-1
ns-phonehome - 0.0.2-1
ns-plug - 0.0.7-1
ns-report - 0.0.1-1
ns-storage - 0.0.3-1
ns-threat_shield - 0.0.2-1
ns-ui - 0.63.0-1
```

**Workaround**
```
uci add_list dhcp.@dnsmasq[0].server=''
uci commit dhcp
```

**Comment by gsanchietti** [comment]
Released: https://github.com/NethServer/nethsecurity/pull/415/commits/efcbaa001244a4a35f6ef4f9625cf3af7519f802
