### ISSUE TITLE
DPI: evaluate removal of subscription

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#473]
A firewall without a valid subscription can't access DPI advanced signatures.

Required changes: when a firewall is unregistered, community signatures should be restored.

If there are any DPI rules using an advanced signature, the signature will not have any effect.

**Comment by andre8244** [comment]
An error occured during QA:
- Enable subscription
- Create a DPI rule and enable some apps (including one or more subscription app)
- Apply pending changes
- Disable subscription
- Go to DPI filter page: an error is show on the UI. Copying the command:
```
/usr/libexec/rpcd/ns.dpi call list-rules
Traceback (most recent call last):
  File "/usr/libexec/rpcd/ns.dpi", line 70, in <module>
    print(json.dumps({'values': dpi.list_rules(e_uci)}))
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nethsec/dpi/__init__.py", line 291, in list_rules
  File "/usr/lib/python3.11/site-packages/nethsec/dpi/__init__.py", line 132, in __load_blocklist
  File "/usr/lib/python3.11/site-packages/nethsec/dpi/__init__.py", line 30, in __load_applications
FileNotFoundError: [Errno 2] No such file or directory: '/etc/netify.d/netify-apps.conf'
```

**Comment by andre8244** [comment]
Verified
