### ISSUE TITLE
IPSec tunnels: can't create tunnel with PPPoE WAN

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#540]
**Steps to reproduce**

- Make sure to configure a PPPoE WAN on a vlan
- Access the "IPsec tunnel" page
- Try to create a new tunnel

**Expected behavior**

The UI should display the drawer and list all available IP addresses inside the "WAN IP address field".

**Actual behavior**

The UI fails on `ns.ipsectunnel list-wans` API call.

Error is:
```
# /usr/libexec/rpcd/ns.ipsectunnel call list-wans
Traceback (most recent call last):
  File "/usr/libexec/rpcd/ns.ipsectunnel", line 380, in <module>
    ret = {"wans": utils.get_all_wan_ips(EUci())}
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nethsec/utils/__init__.py", line 506, in get_all_wan_ips
    ret.append({"device": f'{interface.replace("@","")} ({device})', "ipaddr": ip})
                             ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Components**

Version: 8-23.05.3-ns.0.0.5-rc2

**See also**

https://partner.nethesis.it/t/nethsecurity-8-ed-errore-durante-creazione-tunnel-ipsec/8629

----

Thanks to **Sandro Gregori**

**Comment by gsanchietti** [comment]
Verified.
