### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#920]
Implement High Availability on a 2 node cluster.
The cluster should be composed by:
- one leader node
- one backup node

Supported scenarios:

- multiple WANs with configured static IPs  and DHCP
- multiple LANs
- configuration must be kept in sync from leader do backup node
- automatic switchover from leader to backup
- manual switch from backup to leader

The user should be able to configure the High Availability from the CLI.

#### References:
- [Pull Request #871](https://github.com/NethServer/nethsecurity/pull/871)
- [README](https://github.com/NethServer/nethsecurity/blob/keepalived/packages/ns-ha/README.md)
- [OpenWRT High Availability Documentation](https://openwrt.org/docs/guide-user/network/high-availability)
- [Keepalived Sync Documentation](https://forum.openwrt.org/t/keepalived-sync-docs-and-config-examples/184531)

**Comment by gsanchietti** [comment]
**Test case 1: clean HA cluster install and initialization**
- On two new NethServer nodes with identical hardware, set static LAN IPs (e.g. 192.168.100.238 and 192.168.100.239).
- On the primary node, install the HA package.
- On the primary node, run `ns-ha-config check-primary-node` and verify all requirements are met.
- On the primary node, run `ns-ha-config check-backup-node 192.168.100.239` and verify all requirements are met.
- On the primary node, run `ns-ha-config init-primary-node 192.168.100.238 192.168.100.239 192.168.100.240/24`.
- On the backup node, run `ns-ha-config init-backup-node` and provide the password if prompted.
- On both nodes, run `ns-ha-config status` and verify:
  - Status: enabled
  - Role: primary/backup
  - Current State: master/backup
  - Last Sync Status: Up to Date (after initial sync)
- Possible issues: SSH connectivity, mismatched hardware, missing static IPs, sync failures.

**Test case 2: add and remove WAN interface**
- On the primary node, run `ns-ha-config add-interface wan 192.168.122.49/24 192.168.122.1`.
- On both nodes, verify the WAN interface is present and configured with a fake IP in 169.254.0.0/16.
- On the primary node, run `ns-ha-config show-config` and verify the WAN interface is listed under "Interfaces".
- On the primary node, run `ns-ha-config remove-interface wan`.
- On the primary node, run `ns-ha-config show-config` and verify the WAN interface is removed from HA configuration.
- Possible issues: interface not created, wrong IP assignment, removal not reflected.

**Test case 3: add and remove alias**
- On the primary node, run `ns-ha-config add-alias lan 192.168.100.66/24`.
- On the primary node, run `ns-ha-config show-config` and verify the alias is listed under "Aliases".
- On the primary node, run `ns-ha-config remove-alias lan 192.168.100.66/24`.
- On the primary node, run `ns-ha-config show-config` and verify the alias is removed.
- Possible issues: alias not added/removed, alias not reflected in keepalived config.

**Test case 4: failover and recovery**
- With both nodes running, disconnect the primary node from the network.
- On the backup node, run `ns-ha-config status` and verify:
  - Role: backup
  - Current State: master
  - Virtual IP is now active on the backup node.
- Reconnect the primary node and verify it regains the master role and virtual IP.
- Possible issues: virtual IP not switching, services not starting on backup, split-brain.

**Test case 5: configuration synchronization**
- On the primary node, make a configuration change (e.g. add a firewall rule).
- Wait for synchronization to complete.
- On the backup node, verify the configuration change is present (check `/usr/share/keepalived/rsync/` or relevant config).
- Check `/var/log/messages` for sync logs.
- Possible issues: sync delays, missing files, rsync/SSH errors.

**Test case 6: DHCP and DNS server HA**
- Enable DHCP and DNS server on the primary node.
- Ensure "Force DHCP server start" and "router" options are set to the virtual IP.
- On a client, verify DHCP lease and DNS resolution via the virtual IP.
- Simulate failover and verify DHCP/DNS continue to work via the backup node.
- Possible issues: DHCP not starting, wrong router option, service not failing over.

**Test case 7: unsupported configuration detection**
- On the primary node, configure a PPPoE WAN interface.
- Run `ns-ha-config check-primary-node` and verify it reports the unsupported configuration.
- On the backup node, configure a non-static LAN IP and verify detection.
- Possible issues: unsupported configs not detected, misleading error messages.

**Test case 8: maintenance and reset**
- On the backup node, run `/etc/init.d/keepalived stop` and perform maintenance (e.g. reboot).
- Start keepalived again and verify the node rejoins the cluster.
- On the primary node, run `/etc/init.d/keepalived stop` and verify the backup takes over.
- Run `ns-ha-config reset` on the primary node and verify:
  - keepalived and conntrackd are stopped/disabled
  - configuration files and SSH keys are removed
  - network configuration is unchanged
- Possible issues: services not stopping, reset not cleaning up, backup not taking over.

**Test case 9: backup node limitations**
- On the backup node, verify:
  - No Internet access (cannot resolve DNS, cannot reach controller/portals)
  - Disabled cronjobs (subscription heartbeat, phonehome, remote backup)
- Possible issues: backup node has Internet access, cronjobs not disabled.

**Test case 10: log and troubleshooting checks**
- Trigger a configuration sync and check `/var/log/messages` for `ns-rsync.sh` entries.
- Add/remove an interface and check for corresponding log entries.
- On both nodes, check the bash prompt for `[P]` or `[B]` to distinguish node roles.
- Possible issues: missing logs, prompt not updated, unclear status.

**Test case 11: negative test - sync failure**
- Block SSH port 65022 between nodes.
- On the primary node, trigger a sync and verify `Last Sync Status: SSH Connection Failed`.
- Unblock the port and verify sync resumes.
- Possible issues: sync status not updated, no error reported.

**Test case 12: OpenVPN RoadWarrior and tunnel HA**
- On the primary node, configure an OpenVPN RoadWarrior server and a site-to-site tunnel.
- Connect a client and verify VPN connectivity via the virtual IP.
- Simulate failover (disconnect primary node).
- On the backup node, verify VPN connectivity is maintained and OpenVPN services are running.
- Reconnect the primary node and verify it resumes VPN services.
- Possible issues: VPN not starting on backup, tunnel not restored, client disconnects.

**Test case 13: IPsec tunnel (strongSwan) HA**
- On the primary node, configure an IPsec tunnel.
- Establish the tunnel and verify connectivity.
- Simulate failover.
- On the backup node, verify the tunnel is re-established and traffic flows.
- Possible issues: tunnel not imported/enabled, routes missing, tunnel not restored after failover.

**Test case 14: WireGuard tunnel HA**
- On the primary node, configure a WireGuard tunnel.
- Connect a client and verify connectivity.
- Simulate failover.
- On the backup node, verify the WireGuard interface is enabled and connectivity is restored.
- Possible issues: interface not enabled, keys not synced, tunnel not restored.

**Test case 15: Threat Shield IP (banip) and DNS (adblock) HA**
- On the primary node, enable Threat Shield IP and DNS protection.
- Verify threat lists are downloaded and blocking is active.
- Simulate failover.
- On the backup node, verify threat protection is still enforced.
- Possible issues: lists not synced, blocking not enforced, adblock/banip not running.

**Test case 16: Reverse proxy (nginx) HA**
- On the primary node, configure a reverse proxy rule.
- Access a backend service via the virtual IP and verify correct proxying.
- Simulate failover.
- On the backup node, verify the reverse proxy is still functional.
- Possible issues: nginx config not synced, proxy not working after failover.

**Test case 17: ACME certificates HA**
- On the primary node, request and install an ACME certificate.
- Verify the certificate is used by services (e.g., HTTPS).
- Simulate failover.
- On the backup node, verify the certificate is present and used.
- Possible issues: certificate not synced, services using wrong certificate.

**Test case 18: Users and objects database HA**
- On the primary node, add a user and an object.
- Simulate failover.
- On the backup node, verify the user and object are present.
- Possible issues: database not synced, missing users/objects.

**Test case 19: Netmap HA**
- On the primary node, configure Netmap.
- Verify mapping is active.
- Simulate failover.
- On the backup node, verify Netmap continues to function.
- Possible issues: config not synced, mapping not enforced.

**Test case 20: Flashstart HA**
- On the primary node, configure Flashstart.
- Verify filtering is active.
- Simulate failover.
- On the backup node, verify Flashstart continues to function.
- Possible issues: config not synced, filtering not enforced.

**Test case 21: SNMP server (snmpd) HA**
- On the primary node, enable SNMP server.
- Query SNMP via the virtual IP and verify response.
- Simulate failover.
- On the backup node, verify SNMP server responds via the virtual IP.
- Possible issues: snmpd not running, config not synced.

**Test case 22: NAT helpers**
- On the primary node, configure NAT helpers.
- Verify NAT helpers are active.
- Simulate failover.
- On the backup node, verify NAT helpers.
- Possible issues: helpers not loaded.

**Test case 23: Backup encryption password HA**
- On the primary node, set a backup encryption password.
- Simulate failover.
- On the backup node, verify the encryption password is present.
- Possible issues: password not synced.

**Test case 24: Controller connection (ns-plug) HA**
- On the primary node, connect to the controller.
- Simulate failover.
- On the backup node, verify controller connection is enabled when the node becames active.
- Possible issues: backup node tries to connect to controller.

**Test case 25: Active connections tracking (conntrackd) HA**
- On the primary node, generate active connections (e.g., ongoing downloads).
- Simulate failover.
- On the backup node, verify connections persist (minimal interruption).
- Possible issues: connections dropped, conntrackd not syncing state.

**Comment by cotosso** [comment]
**Test case 2: add and remove WAN interface**
Woks as expected

**Comment by cotosso** [comment]
**Test case 3: add and remove alias**
All commands work as expected, except for the command `ns-ha-config show-config` that doesn't show any alias
```
root@fw1 [P]:~# ip a s eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 40:62:31:08:46:f1 brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.238/24 brd 192.168.100.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.100.240/24 scope global secondary eth0:ha
       valid_lft forever preferred_lft forever
    inet 192.168.100.66/24 scope global secondary eth0:ha
       valid_lft forever preferred_lft forever
root@fw1 [P]:~# ns-ha-config show-config

Current configuration

Interfaces:
  Interface: wan, Device: eth1, Virtual IP: 192.168.20.63/24
  Interface: lan, Device: eth0, Virtual IP: 192.168.100.240/24
  Interface: ospiti2, Device: eth0.10, Virtual IP: 192.168.98.1/24

Aliases:
  None

-----------------------------------------------------------------

Not configured

Interfaces:
  None

Aliases:
  None


```

**Comment by cotosso** [comment]
**Test case 5: configuration synchronization**
Sync works as expected, I tested it with firewall rules.

I've noticed that when switched to backup firewall, if I change something on the rules, then the primary comes up again rules are not re-synced until I make some changes on the master.

**Comment by cotosso** [comment]
**Test case 6: DHCP and DNS server HA** 
OK: Everything seems to work as expected

**Comment by cotosso** [comment]
**Test case 8: maintenance and reset**

** _/etc/init.d/keepalived stop_ for maintenance : OK**

- Run `/etc/init.d/keepalived stop` on backup node, reboot, everything went fine
at system restart keepalived automatically restarted and rejoined the cluster

- Run `/etc/init.d/keepalived stop` on primary  node : everything went fine

**HA-reset : KO**
```
root@ha-sen-home [P]:~# ns-ha-config reset
Are you sure you want to reset the HA configuration? This action cannot be undone. (yes/no): yes
Resetting HA configuration... Traceback (most recent call last):
  File "/usr/libexec/rpcd/ns.ha", line 1008, in <module>
    ret = reset(args.get('role'), args.get('pubkey'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/libexec/rpcd/ns.ha", line 939, in reset
    output, error = execute_remote_command(f"echo '{command}' | /usr/libexec/rpcd/ns.ha call reset", backup_node_ip=backup_node_ip, port=port)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/libexec/rpcd/ns.ha", line 175, in execute_remote_command
    proc = subprocess.run(['dropbearconvert', 'dropbear', 'openssh', private_key_path, "-"], check=True, capture_output=True, text=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['dropbearconvert', 'dropbear', 'openssh', '/etc/keepalived/keys/id_rsa', '-']' returned non-zero exit status 1.
ERROR
Failed to reset the HA configuration.
```

**Comment by cotosso** [comment]
**Test case 9: backup node limitations** 


On the backup node, verify:
No Internet access (cannot resolve DNS, cannot reach controller/portals) : **confirmed**
```
root@ha-sen-home [S]:~# ip ro
169.254.0.0/16 dev eth1 proto kernel scope link src 169.254.0.2 
192.168.100.0/24 dev br-lan proto kernel scope link src 192.168.100.239 
```

Disabled cronjobs (subscription heartbeat, phonehome, remote backup) : **confirmed**
```
root@ha-sen-home [S]:~# cat /etc/crontabs/root | grep "#"
#*/10 * * * * sleep $(( RANDOM % 60 )); /usr/sbin/send-heartbeat
#0 0 * * * /etc/init.d/acme start
#02 2 * * * sleep $(( RANDOM % 1800 )); /usr/sbin/send-backup
#05 3 * * * sleep $(( RANDOM % 1800 )); /usr/sbin/send-inventory
#10 4 * * * sleep $(( RANDOM % 1800 )); /usr/sbin/send-phonehome
```


Every test works as reported in the test case , but **I believe it is preferable to allow the backup firewall to access the Internet even when it is not active**, so that:

- it can download all automatic updates and remain fully up to date, including security patches, bug fixes, and any service-related lists, ensuring it is ready for failover in optimal conditions;

- it can communicate with the NOC, allowing its monitoring even if it is not actively processing traffic. 
- Without this visibility, we wouldn't be able to determine if the device has gone offline due to a failure.

A static route via the primary node might be sufficient to provide this Internet access.

**Comment by cotosso** [comment]
**Test case 10: log and troubleshooting checks: OK**
Everything seems to work as expected

**Comment by gsanchietti** [comment]
New image that fixes test case 8: https://github.com/NethServer/nethsecurity/actions/runs/14885094944/artifacts/3078691155
It also includes the UI fix for SSH: now the UI show the main SSH instance and not the one used by keepalived.

**Comment by cotosso** [comment]
**Test case 12: OpenVPN RoadWarrior and tunnel HA**

**OpenVPN RoadWarrior: OK**
Everything works as expected, tested with all authentication modes (only with local database):
* Certificate only
* User, password
* User, password, certificate
* User, certificate, OTP

**OpenVPN tunnel : to be tested**

**Comment by cotosso** [comment]
> This is a regression introduced by LAN/WAN selection. Fixed in this build: https://github.com/NethServer/nethsecurity/actions/runs/15279615380

I tested it: it works like expected

**Comment by cotosso** [comment]
**Test case 15: Threat Shield IP (banip) and DNS (adblock) HA**

Threat Shield IP (banip) : OK
Threat Shield DNS (adblock) : TO TEST

**Comment by gsanchietti** [comment]
Another fix for IPsec and routes: they were both disabled when switching back from secondary to primary.
Build: https://github.com/NethServer/nethsecurity/actions/runs/15341748720

**Comment by cotosso** [comment]
Test case 13: IPsec tunnel (strongSwan) HA : OK
after last modification everything works as expected

**Comment by cotosso** [comment]
**Test case 24: Controller connection (ns-plug) HA : OK**

Everything works as expected
