### ISSUE TITLE
Road Warrior client migration halts when a user certificate is missing or invalid

### ISSUE THREAD

**Issue by francio87** [NethServer/nethsecurity#991]
**Description**:
During the migration process, if the Road Warrior server is configured to use certificate based authentication and a user certificate is missing or invalid, the Road Warrior client migration halts at the problematic user. While the overall migration process continues, this issue interrupts the Road Warrior client import.

**Steps to Reproduce**:  
1. Use an export file with a Road Warrior user entry where the certificate (`crt`) is `null`. For example:  
   ```json
   {
     "password": "",
     "name": "my&user",
     "crt": null,
     "2fa": null,
     "key": null,
     "ipaddr": "172.16.10.94",
     "enabled": "1"
   }
   ```  
2. Start the migration process.  
3. Observe that the Road Warrior client migration halts on the problematic user. However, the overall migration process continues for other components.  

**Expected Behavior**:  
The migration process should log a warning or error for the problematic user, skip the invalid entry, and continue processing the remaining valid users.  

**Actual Behavior**:  
The Road Warrior client migration halts at the problematic user. The following error appears in `migration.log`:  
```sh
Creating OpenVPN Road Warrior user user2
Creating OpenVPN Road Warrior user my&user
Traceback (most recent call last):
  File "/usr/share/ns-migration/40openvpn", line 189, in <module>
    save_cert(os.path.join(cert_dir, f'private/{user["name"]}.key'), user['key'])
  File "/usr/share/ns-migration/40openvpn", line 23, in save_cert
    f.write(data)
TypeError: write() argument must be str, not None
```

---

Ref:
- [Internal discussion](https://mattermost.nethesis.it/nethesis/pl/s91mowwsatdwzber48en5isr3y)

**Components**

Package affected: `ns-migration <= 0.0.17`

Additional validation should be added [here](https://github.com/NethServer/nethsecurity/blob/ee52d04e5156eecba1c523bee2f24df7d9d7d0c7/packages/ns-migration/files/scripts/openvpn#L177).

**Comment by Tbaile** [comment]
Image: [23.05.5-ns.1.4.1-1-g091d93d3](https://github.com/NethServer/nethsecurity/actions/runs/12648819723/artifacts/2394711132)

Check that the issue is solved.

**Comment by gsanchietti** [comment]
The issue is not reproducible: verified.
